no_debug: '0'
domain_ends_at: '03.07'
time_zone: Moscow
ip: '85.95.167.32'
default_user_ip: '89.169.75.76'
host_test: '127.0.0.1:3000'
host_development: '127.0.0.1:3000'
host_staging: 'https://stage.xn-----mlcc9ajg5df.xn--p1ai'
host_production: 'https://xn-----mlcc9ajg5df.xn--p1ai'
max_sms_cost_rub: '3'
advs_per_page: '25'
notifications_per_page: '50'
feedbacks_per_page: '50'
incomings_per_page: '25'
outgoings_per_page: '25'
refunds_per_page: '25'
users_per_page: '25'
photos_per_adv: '10'
videos_per_adv: '25'
comparisons_per_user: '100'
max_avatar_size_mb: '5'
max_advs_for_unconfirmed_user: '5'
photos_ext_white_list: 'jpg jpeg png'
min_avatar_width: '200'
min_avatar_height: '200'
max_avatar_width: '3648'
max_avatar_height: '2736'
max_photo_size_mb: '10'
min_photo_width: '320'
max_photo_width: '6016'
max_photo_height: '4000'
min_photo_height: '240'
max_output_photo_width: '1920'
max_output_photo_height: '1080'
max_photo_description_chars: '160'
max_total_photos_size_for_forced_adv_kb: '1250'
max_total_photos_size_gb: '150'
thumb_width: '200'
thumb_height: '133'
default_search_lattitude: '55.7539'
default_search_longitude: '37.6203'
default_search_radius_m: '10000'
maximum_search_radius_m: '500000'
maximum_named_search_per_user: '50'
max_phones_count_per_user: '6'
max_geos_count_per_user: '150'
max_price_watches_per_user: '150'
send_confirm_phone_code_interval: '3'
phone_views: '20'
promo_ends_at: '01.09.2019'
emission_per_day: '50'
sms_on_ram_free_less_mb: '1000'
pay_for_sharing: 'false'
display_map_slider: 'false'
vk_api_version: '5.0'
payment_module: 'walletone'
recaptcha_enable: 'false'
recaptcha_enable_on_development: 'true'
recaptcha_enable_on_sign_in: 'true'
recaptcha_score: '0.2'
send_email_on_adv_expired: 'false'
refund_tax: '0.01'
admin_phone: '+79520765032'
advs_minimum_count: '50000'
critical_active_advs_count: '50000'
critical_scrapy_unprocessed_count: '20000'
critical_disk_space_percent: '5'
use_tor_on_dev: 'true'
tor_proxy: '172.10.0.23'
dev_tor_proxy: '192.168.0.231'
tor_port: '8118'
redis_counters_history_depth: '520'